using System.Xml.Linq;
using FluentAssertions;
using Winhance.Infrastructure.Features.Autounattend;
using Xunit;

namespace Winhance.Infrastructure.Tests.Autounattend;

public class AutounattendDocumentTests
{
    private static readonly XNamespace U = AutounattendDocument.Unattend;

    [Fact]
    public void Skeleton_has_the_seven_passes_in_setup_order_and_nothing_else()
    {
        var doc = AutounattendDocument.NewSkeleton();

        doc.Root!.Name.Should().Be(U + "unattend");
        doc.Root.Elements().Select(e => (string?)e.Attribute("pass")).Should().Equal(
            "offlineServicing", "windowsPE", "generalize", "specialize", "auditSystem", "auditUser", "oobeSystem");
        doc.Root.Elements().Should().OnlyContain(e => e.Name == U + "settings" && !e.HasElements);
        doc.Root.Nodes().OfType<XComment>().Single().Value.Should().Be(" XML Generated by Winhance https://github.com/memstechtips/Winhance ");
    }

    [Fact]
    public void Component_is_created_once_with_the_standard_attributes()
    {
        var settings = AutounattendDocument.NewSkeleton().Pass("specialize");

        var first = settings.Component("Microsoft-Windows-Deployment");
        var second = settings.Component("Microsoft-Windows-Deployment");

        second.Should().BeSameAs(first);
        settings.Elements(U + "component").Should().ContainSingle();
        first.Attributes().Select(a => (a.Name.LocalName, a.Value)).Should().Equal(
            ("name", "Microsoft-Windows-Deployment"),
            ("processorArchitecture", "amd64"),
            ("publicKeyToken", "31bf3856ad364e35"),
            ("language", "neutral"),
            ("versionScope", "nonSxS"));
    }

    [Fact]
    public void Child_lands_in_schema_order_whatever_the_call_order()
    {
        var shell = AutounattendDocument.NewSkeleton().Pass("oobeSystem").Component("Microsoft-Windows-Shell-Setup");

        shell.Child("FirstLogonCommands");
        shell.Child("OOBE");
        shell.Child("TimeZone");
        shell.Child("OOBE");

        shell.Elements().Select(e => e.Name.LocalName).Should().Equal("TimeZone", "OOBE", "FirstLogonCommands");
    }

    [Fact]
    public void SetOobe_orders_flags_the_way_the_template_did_and_replaces_in_place()
    {
        var shell = AutounattendDocument.NewSkeleton().Pass("oobeSystem").Component("Microsoft-Windows-Shell-Setup");

        shell.SetOobe("ProtectYourPC", "3");
        shell.SetOobe("HideOnlineAccountScreens", "true");
        shell.SetOobe("HideEULAPage", "true");
        shell.SetOobe("HideEULAPage", "false");

        var oobe = shell.Element(U + "OOBE")!;
        oobe.Elements().Select(e => e.Name.LocalName).Should().Equal("HideEULAPage", "HideOnlineAccountScreens", "ProtectYourPC");
        oobe.Element(U + "HideEULAPage")!.Value.Should().Be("false");
    }

    [Fact]
    public void ElementPath_walks_component_order_then_appends_the_deeper_names()
    {
        var setup = AutounattendDocument.NewSkeleton().Pass("windowsPE").Component("Microsoft-Windows-Setup");

        setup.ElementPath("UserData/ProductKey/Key").Value = "x";
        setup.ElementPath("UserData/ProductKey/WillShowUI").Value = "Always";
        setup.ElementPath("UserData/AcceptEula").Value = "true";

        var userData = setup.Element(U + "UserData")!;
        userData.Elements().Select(e => e.Name.LocalName).Should().Equal("ProductKey", "AcceptEula");
        userData.Element(U + "ProductKey")!.Elements().Select(e => e.Name.LocalName).Should().Equal("Key", "WillShowUI");
        userData.Element(U + "ProductKey")!.Element(U + "Key")!.Value.Should().Be("x");
    }

    [Fact]
    public void RunSynchronous_commands_are_numbered_in_insertion_order()
    {
        var deployment = AutounattendDocument.NewSkeleton().Pass("specialize").Component("Microsoft-Windows-Deployment");

        deployment.AddRunSynchronousCommand("cmd.exe /c one", "first");
        deployment.AddRunSynchronousCommand("cmd.exe /c two");

        var commands = deployment.Element(U + "RunSynchronous")!.Elements(U + "RunSynchronousCommand").ToList();
        commands.Select(c => (string?)c.Element(U + "Order")).Should().Equal("1", "2");
        commands.Should().OnlyContain(c => (string?)c.Attribute(AutounattendDocument.Wcm + "action") == "add");
        commands[0].Elements().Select(e => e.Name.LocalName).Should().Equal("Order", "Description", "Path");
        commands[1].Elements().Select(e => e.Name.LocalName).Should().Equal("Order", "Path");
        commands[1].Element(U + "Path")!.Value.Should().Be("cmd.exe /c two");
    }

    [Fact]
    public void FirstLogon_commands_are_numbered_and_carry_no_action_attribute()
    {
        var shell = AutounattendDocument.NewSkeleton().Pass("oobeSystem").Component("Microsoft-Windows-Shell-Setup");

        shell.AddFirstLogonCommand("cmd.exe /c one", "first");
        shell.AddFirstLogonCommand("cmd.exe /c two");

        var commands = shell.Element(U + "FirstLogonCommands")!.Elements(U + "SynchronousCommand").ToList();
        commands.Select(c => (string?)c.Element(U + "Order")).Should().Equal("1", "2");
        commands.Should().OnlyContain(c => !c.HasAttributes);
        commands[0].Elements().Select(e => e.Name.LocalName).Should().Equal("Order", "Description", "CommandLine");
    }

    [Fact]
    public void SetSetting_creates_then_replaces()
    {
        var userData = AutounattendDocument.NewSkeleton().Pass("windowsPE").Component("Microsoft-Windows-Setup").Child("UserData");

        userData.SetSetting("AcceptEula", "true");
        userData.SetSetting("AcceptEula", "false");

        userData.Elements(U + "AcceptEula").Should().ContainSingle().Which.Value.Should().Be("false");
    }

    [Fact]
    public void Extensions_is_created_once_after_the_passes()
    {
        var doc = AutounattendDocument.NewSkeleton();

        var extensions = doc.Extensions();

        doc.Extensions().Should().BeSameAs(extensions);
        extensions.Name.Should().Be(AutounattendDocument.WinhanceExtensions + "Extensions");
        doc.Root!.Elements().Last().Should().BeSameAs(extensions);
    }
}
