#Requires -Version 5.1
<#
    Probe-WinhanceDefaults.ps1  --  Winhance fresh-install registry ground-truth probe

    WHAT THIS DOES
      Reads (never writes) every registry location the Winhance setting catalog detects from,
      and records for each one whether the value is PRESENT, ABSENT, or whether the parent KEY
      IS MISSING entirely. The point of the exercise is that "absent" is NOT the same as "off":
      Windows ships many settings with no registry value written at all, and only writes one
      once something explicitly sets it. This probe tells us which catalog targets are genuinely
      absent on a clean install so the catalog's WindowsDefault detection can be corrected.

    ############################################################################
    #  RUN THIS AS YOUR NORMAL USER.  DO NOT "RUN AS ADMINISTRATOR".           #
    #                                                                          #
    #  Most catalog targets live in HKEY_CURRENT_USER. An elevated shell reads #
    #  the ADMINISTRATOR account's HKCU, which is a different hive, and every   #
    #  per-user answer in the output would be silently wrong. The script       #
    #  refuses to run elevated for exactly this reason.                        #
    ############################################################################

    HOW TO RUN
      1. Copy this single file to the clean machine (Desktop is fine). Nothing to install.
      2. Open a NORMAL (non-elevated) PowerShell window.
      3. Run:
             powershell -ExecutionPolicy Bypass -File .\Probe-WinhanceDefaults.ps1
      4. Send back the .json file it writes next to itself. The path is printed at the end.

    STRICTLY READ-ONLY
      This script opens registry keys read-only and never writes, creates or deletes anything.
      powercfg targets are deliberately NOT probed, because unhiding a hidden powercfg setting
      requires WRITING Attributes = 0 to the registry, which would no longer be a clean-install
      reading. Those targets are recorded as "NotProbed".

    Generated by tests/Winhance.Infrastructure.Tests/Catalog/CatalogProbeManifestGeneratorTests.cs
    from extras/probe/Probe-WinhanceDefaults.template.ps1. Do not hand-edit the generated file;
    edit the template and regenerate.
#>

[CmdletBinding()]
param(
    # Only for a machine with UAC disabled, where an administrator's shell still reads that same
    # user's HKCU. Recorded in the output so the result can be discounted if it was a mistake.
    [switch] $AllowElevated,

    # Where to write the .json. Defaults to the folder this script lives in, then Desktop, then TEMP.
    [string] $OutputDir
)

$ErrorActionPreference = 'Stop'
Set-Variable -Name ProbeSchemaVersion -Value 1 -Option Constant

# ---------------------------------------------------------------------------------------------
# Embedded catalog manifest (generated -- see header). Single-quoted here-string: literal, no
# expansion. The generator guarantees the JSON is one line of pure ASCII with no apostrophes,
# so it can never contain a here-string terminator.
# ---------------------------------------------------------------------------------------------
$ManifestJson = @'
@@MANIFEST_JSON@@
'@

# =============================================================================================
# JSON output writer
#
# Hand-rolled rather than ConvertTo-Json on purpose:
#   - ConvertTo-Json in PS 5.1 defaults to -Depth 2 and SILENTLY flattens anything deeper into
#     "System.Object[]" strings, which would quietly destroy most of this output.
#   - PS 5.1's serializer has a maxJsonLength ceiling that this output could approach.
#   - We want byte[] as hex and every non-ASCII character escaped, so the result file is ASCII.
# =============================================================================================

function ConvertTo-JsonStringLiteral {
    param([string] $Text)
    $sb = New-Object System.Text.StringBuilder
    [void]$sb.Append('"')
    foreach ($ch in $Text.ToCharArray()) {
        $code = [int]$ch
        if ($ch -eq '"') { [void]$sb.Append('\"') }
        elseif ($ch -eq '\') { [void]$sb.Append('\\') }
        elseif ($code -lt 32 -or $code -gt 126) { [void]$sb.Append('\u' + $code.ToString('x4')) }
        else { [void]$sb.Append($ch) }
    }
    [void]$sb.Append('"')
    return $sb.ToString()
}

function ConvertTo-JsonText {
    param($Value)

    if ($null -eq $Value) { return 'null' }

    # ConvertFrom-Json hands back PSCustomObjects. Unwrapping to .BaseObject is NOT enough: a bare
    # PSCustomObject matches none of the type tests below and would fall through to [string]$Value,
    # silently serializing as "". Walk its properties into a real JSON object instead.
    if ($null -ne $Value.PSObject -and
        $Value.PSObject.BaseObject -is [System.Management.Automation.PSCustomObject]) {
        $parts = @()
        foreach ($p in $Value.PSObject.Properties) {
            $parts += (ConvertTo-JsonStringLiteral ([string]$p.Name)) + ':' + (ConvertTo-JsonText $p.Value)
        }
        return '{' + ($parts -join ',') + '}'
    }
    if ($Value -is [System.Management.Automation.PSObject] -and $null -ne $Value.BaseObject) {
        $Value = $Value.BaseObject
    }

    if ($Value -is [bool]) { if ($Value) { return 'true' } else { return 'false' } }
    if ($Value -is [string]) { return (ConvertTo-JsonStringLiteral $Value) }

    if ($Value -is [byte] -or $Value -is [int16] -or $Value -is [uint16] -or
        $Value -is [int32] -or $Value -is [uint32] -or $Value -is [int64] -or $Value -is [uint64]) {
        return $Value.ToString([System.Globalization.CultureInfo]::InvariantCulture)
    }
    if ($Value -is [double] -or $Value -is [single] -or $Value -is [decimal]) {
        return $Value.ToString('R', [System.Globalization.CultureInfo]::InvariantCulture)
    }

    if ($Value -is [System.Collections.IDictionary]) {
        $parts = @()
        foreach ($k in $Value.Keys) {
            $parts += (ConvertTo-JsonStringLiteral ([string]$k)) + ':' + (ConvertTo-JsonText $Value[$k])
        }
        return '{' + ($parts -join ',') + '}'
    }

    # Must come AFTER the string test -- string is IEnumerable.
    if ($Value -is [System.Collections.IEnumerable]) {
        $parts = @()
        foreach ($item in $Value) { $parts += (ConvertTo-JsonText $item) }
        return '[' + ($parts -join ',') + ']'
    }

    return (ConvertTo-JsonStringLiteral ([string]$Value))
}

# =============================================================================================
# Elevation gate -- see the banner at the top of this file.
# =============================================================================================

$identity = [System.Security.Principal.WindowsIdentity]::GetCurrent()
$principal = New-Object System.Security.Principal.WindowsPrincipal($identity)
$isElevated = $principal.IsInRole([System.Security.Principal.WindowsBuiltInRole]::Administrator)

if ($isElevated -and -not $AllowElevated) {
    Write-Host ''
    Write-Host '  REFUSING TO RUN: this PowerShell window is elevated (running as Administrator).' -ForegroundColor Red
    Write-Host ''
    Write-Host '  Most of the settings this probe reads live in HKEY_CURRENT_USER. An elevated shell'
    Write-Host '  reads the ADMINISTRATOR account''s HKCU hive, not yours, so every per-user reading'
    Write-Host '  would be wrong in a way that looks completely plausible in the output.'
    Write-Host ''
    Write-Host '  Close this window, open a NORMAL PowerShell window, and run:'
    Write-Host '      powershell -ExecutionPolicy Bypass -File .\Probe-WinhanceDefaults.ps1' -ForegroundColor Yellow
    Write-Host ''
    Write-Host '  (If and ONLY if this machine has UAC switched off entirely -- in which case an'
    Write-Host '   administrator shell really is reading your own HKCU -- re-run with -AllowElevated.)'
    Write-Host ''
    exit 2
}

# =============================================================================================
# Machine identity -- a probe result is meaningless without knowing exactly which install it
# came from (edition, build, patch level, locale, battery, VM or metal).
# =============================================================================================

function Get-HklmString {
    param([string] $SubKey, [string] $Name)
    try {
        $base = [Microsoft.Win32.RegistryKey]::OpenBaseKey(
            [Microsoft.Win32.RegistryHive]::LocalMachine, [Microsoft.Win32.RegistryView]::Registry64)
        try {
            $k = $base.OpenSubKey($SubKey, $false)
            if ($null -eq $k) { return $null }
            try { $v = $k.GetValue($Name, $null) } finally { $k.Close() }
            if ($null -eq $v) { return $null }
            return [string]$v
        } finally { $base.Close() }
    } catch { return $null }
}

$cvKey = 'SOFTWARE\Microsoft\Windows NT\CurrentVersion'
$buildNumber = 0
$ubr = 0
[void][int]::TryParse((Get-HklmString $cvKey 'CurrentBuildNumber'), [ref]$buildNumber)
[void][int]::TryParse((Get-HklmString $cvKey 'UBR'), [ref]$ubr)

# TryParse returns $false rather than throwing, so a failed read leaves $buildNumber at 0. That is
# not survivable: every build-scoped WindowsDefault role would fail to match, the headline finding
# would come back empty, and the run would LOOK successful. Fail loudly instead.
if ($buildNumber -eq 0) {
    Write-Host ''
    Write-Host '  FAILED to read CurrentBuildNumber from HKLM. Cannot evaluate build-scoped defaults.' -ForegroundColor Red
    Write-Host '  Without it this probe would report a plausible-looking but empty result.' -ForegroundColor Red
    Write-Host ''
    exit 5
}

$hasBattery = $null
$computerModel = $null
$computerManufacturer = $null
try {
    $batteries = @(Get-CimInstance -ClassName Win32_Battery -ErrorAction Stop)
    $hasBattery = ($batteries.Count -gt 0)
} catch {
    try {
        $batteries = @(Get-WmiObject -Class Win32_Battery -ErrorAction Stop)
        $hasBattery = ($batteries.Count -gt 0)
    } catch { $hasBattery = $null }
}
try {
    $cs = Get-CimInstance -ClassName Win32_ComputerSystem -ErrorAction Stop
    $computerModel = [string]$cs.Model
    $computerManufacturer = [string]$cs.Manufacturer
} catch { }

$machine = [ordered]@{
    probedUtc            = (Get-Date).ToUniversalTime().ToString('yyyy-MM-ddTHH:mm:ssZ')
    computerName         = [string]$env:COMPUTERNAME
    userName             = [string]$env:USERNAME
    userSid              = [string]$identity.User.Value
    isElevated           = [bool]$isElevated
    elevationOverride    = [bool]$AllowElevated
    buildNumber          = $buildNumber
    ubr                  = $ubr
    productName          = Get-HklmString $cvKey 'ProductName'
    displayVersion       = Get-HklmString $cvKey 'DisplayVersion'
    releaseId            = Get-HklmString $cvKey 'ReleaseId'
    editionId            = Get-HklmString $cvKey 'EditionID'
    installationType     = Get-HklmString $cvKey 'InstallationType'
    buildLabEx           = Get-HklmString $cvKey 'BuildLabEx'
    osVersion            = [string][System.Environment]::OSVersion.Version
    architecture         = [string]$env:PROCESSOR_ARCHITECTURE
    is64BitOs            = [bool][System.Environment]::Is64BitOperatingSystem
    is64BitProcess       = [bool][System.Environment]::Is64BitProcess
    currentCulture       = [string][System.Globalization.CultureInfo]::CurrentCulture.Name
    installedUICulture   = [string][System.Globalization.CultureInfo]::InstalledUICulture.Name
    hasBattery           = $hasBattery
    computerManufacturer = $computerManufacturer
    computerModel        = $computerModel
    powerShellVersion    = [string]$PSVersionTable.PSVersion
}

Write-Host ''
Write-Host 'Winhance fresh-install defaults probe' -ForegroundColor Cyan
Write-Host ('  Machine : {0}  ({1} {2})' -f $machine.computerName, $machine.computerManufacturer, $machine.computerModel)
Write-Host ('  Windows : {0}  build {1}.{2}  edition {3}  {4}' -f `
    $machine.productName, $machine.buildNumber, $machine.ubr, $machine.editionId, $machine.displayVersion)
Write-Host ('  User    : {0}  (elevated: {1})  battery: {2}' -f $machine.userName, $machine.isElevated, $machine.hasBattery)
Write-Host ''

# =============================================================================================
# Manifest
# =============================================================================================

Write-Host 'Parsing embedded catalog manifest...'
try {
    $manifest = $ManifestJson | ConvertFrom-Json
} catch {
    Write-Host ''
    Write-Host ('  FAILED to parse the embedded manifest: {0}' -f $_.Exception.Message) -ForegroundColor Red
    Write-Host '  The script file is probably truncated or corrupted in transit. Re-copy it.' -ForegroundColor Red
    exit 3
}
$settings = @($manifest.settings)
Write-Host ('  {0} settings, catalog manifest schema v{1}.' -f $settings.Count, $manifest.schemaVersion)
Write-Host ''

# =============================================================================================
# Registry reading
#
# THE ONE RULE THAT MATTERS: absent is tested with `$null -eq $value`, NEVER with truthiness.
# A DWORD of 0 and an empty REG_SZ are both FALSY in PowerShell, so `if (-not $value)` would
# report them as absent -- inverting the exact finding this probe exists to make.
# =============================================================================================

$baseKeyCache = @{}

function Get-BaseKey {
    param([string] $HiveToken)
    if ($baseKeyCache.ContainsKey($HiveToken)) { return $baseKeyCache[$HiveToken] }

    $hive = $null
    switch ($HiveToken) {
        'HKEY_CURRENT_USER'  { $hive = [Microsoft.Win32.RegistryHive]::CurrentUser }
        'HKCU'               { $hive = [Microsoft.Win32.RegistryHive]::CurrentUser }
        'HKEY_LOCAL_MACHINE' { $hive = [Microsoft.Win32.RegistryHive]::LocalMachine }
        'HKLM'               { $hive = [Microsoft.Win32.RegistryHive]::LocalMachine }
        'HKEY_CLASSES_ROOT'  { $hive = [Microsoft.Win32.RegistryHive]::ClassesRoot }
        'HKCR'               { $hive = [Microsoft.Win32.RegistryHive]::ClassesRoot }
        'HKEY_USERS'         { $hive = [Microsoft.Win32.RegistryHive]::Users }
        'HKU'                { $hive = [Microsoft.Win32.RegistryHive]::Users }
        'HKEY_CURRENT_CONFIG'{ $hive = [Microsoft.Win32.RegistryHive]::CurrentConfig }
        'HKCC'               { $hive = [Microsoft.Win32.RegistryHive]::CurrentConfig }
        default              { return $null }
    }

    # Registry64 explicitly: if this ever runs under 32-bit PowerShell, the default view would
    # silently redirect HKLM\SOFTWARE reads into WOW6432Node and produce wrong answers.
    $key = [Microsoft.Win32.RegistryKey]::OpenBaseKey($hive, [Microsoft.Win32.RegistryView]::Registry64)
    $baseKeyCache[$HiveToken] = $key
    return $key
}

function ConvertTo-RecordedValue {
    param($Raw)
    if ($null -eq $Raw) { return $null }
    if ($Raw -is [byte[]]) {
        $hex = New-Object System.Text.StringBuilder
        foreach ($b in $Raw) { [void]$hex.Append($b.ToString('X2')) }
        return [ordered]@{ '$bytes' = $hex.ToString(); length = $Raw.Length }
    }
    if ($Raw -is [string[]]) {
        $out = @()
        foreach ($s in $Raw) { $out += [string]$s }
        # Comma operator, deliberately: a bare `return $out` writes each element to the pipeline, so a
        # single-entry REG_MULTI_SZ would come back as a plain string and an EMPTY one as $null -- the
        # record would read status "Present" with a null value, which is precisely the
        # present-but-looks-absent ambiguity this whole probe exists to eliminate.
        return ,([string[]]$out)
    }
    if ($Raw -is [int32] -or $Raw -is [int64] -or $Raw -is [uint32] -or $Raw -is [uint64]) { return $Raw }
    return [string]$Raw
}

# Reads ONE path. Returns an ordered hashtable describing the tri-state.
#   status: 'KeyMissing' | 'ValueAbsent' | 'Present' | 'KeyPresent' | 'Error'
#   'KeyPresent' is for a ValueName-less target, whose state IS key existence.
function Read-OnePath {
    param([string] $Path, [string] $ValueName, [bool] $KeyExistenceOnly, [bool] $EnumerateSubKeys)

    $result = [ordered]@{
        path        = $Path
        status      = 'Error'
        value       = $null
        rawValue    = $null
        valueKind   = $null
        subKeys     = $null
        error       = $null
    }

    try {
        $sep = $Path.IndexOf('\')
        if ($sep -lt 1) { $result.error = 'Malformed path (no hive separator).'; return $result }
        $hiveToken = $Path.Substring(0, $sep).ToUpperInvariant()
        $subPath = $Path.Substring($sep + 1)

        $base = Get-BaseKey $hiveToken
        if ($null -eq $base) { $result.error = ('Unknown registry hive: {0}' -f $hiveToken); return $result }

        $key = $base.OpenSubKey($subPath, $false)
        if ($null -eq $key) { $result.status = 'KeyMissing'; return $result }

        try {
            if ($EnumerateSubKeys) {
                $names = @($key.GetSubKeyNames())
                $result.subKeys = $names
            }

            # A target whose ValueName is NULL encodes its state as key existence, not a stored value.
            #
            # This MUST NOT be an IsNullOrEmpty test. Four catalog targets declare ValueName as the EMPTY
            # STRING, which means the key's (Default) value and has to be read like any other value --
            # RegTargetReader branches on `is null`, not on emptiness. PowerShell cannot tell the two apart
            # once the value has been through a [string] cast, since [string]$null is "", so the manifest
            # carries the distinction as its own boolean and we trust that instead of re-deriving it.
            if ($KeyExistenceOnly) {
                $result.status = 'KeyPresent'
                return $result
            }

            $raw = $key.GetValue($ValueName, $null)

            # $null -eq, not truthiness. DWORD 0 and "" are falsy but PRESENT.
            if ($null -eq $raw) {
                $result.status = 'ValueAbsent'
                return $result
            }

            $result.status = 'Present'
            $result.value = ConvertTo-RecordedValue $raw
            try { $result.valueKind = [string]$key.GetValueKind($ValueName) } catch { }

            # REG_EXPAND_SZ: GetValue expands by default (mirroring what the app reads), but the
            # stored template is what actually distinguishes a Windows default from a user edit.
            if ($result.valueKind -eq 'ExpandString') {
                try {
                    $rawUnexpanded = $key.GetValue(
                        $ValueName, $null, [Microsoft.Win32.RegistryValueOptions]::DoNotExpandEnvironmentNames)
                    $result.rawValue = ConvertTo-RecordedValue $rawUnexpanded
                } catch { }
            }
            return $result
        } finally {
            $key.Close()
        }
    } catch {
        $result.status = 'Error'
        $result.error = [string]$_.Exception.Message
        return $result
    }
}

# Mirrors Winhance.Core RegTargetReader.OrderHklmFirst: mirror paths fold HKLM-first, and the
# first non-null read wins. Per-path detail is kept regardless -- knowing that Windows writes
# one mirror and not the other is a large part of what we are trying to learn here.
function Get-HklmFirstOrder {
    param([string[]] $Paths)
    $hklm = @()
    $rest = @()
    foreach ($p in $Paths) {
        if ($p.ToUpperInvariant().StartsWith('HKEY_LOCAL_MACHINE')) { $hklm += $p } else { $rest += $p }
    }
    return @($hklm + $rest)
}

# =============================================================================================
# Probe every target
# =============================================================================================

$results = @()
$counts = [ordered]@{
    Present = 0; ValueAbsent = 0; KeyMissing = 0; KeyPresent = 0; Error = 0; NotProbed = 0
}
$settingIndex = 0
$total = $settings.Count

foreach ($setting in $settings) {
    $settingIndex++
    if (($settingIndex % 40) -eq 0) {
        Write-Progress -Activity 'Probing catalog targets' -Status ('{0} / {1}' -f $settingIndex, $total) `
            -PercentComplete ([int](100 * $settingIndex / $total))
    }

    $targetResults = @()
    foreach ($target in @($setting.targets)) {
        $tr = [ordered]@{
            key            = [string]$target.key
            joinKey        = [string]$target.joinKey
            kind           = [string]$target.kind
            status         = 'NotProbed'
            effectiveValue = $null
            effectivePath  = $null
            valueKind      = $null
            paths          = @()
            note           = $null
        }

        if ($target.kind -ne 'Registry') {
            # powercfg is skipped deliberately: unhiding a hidden powercfg setting requires a
            # registry WRITE, which would stop this being a clean-install reading. Scheduled tasks
            # are read below, separately from the registry pass.
            $tr.note = 'Not probed in v1 (see script header).'
            $counts.NotProbed++
            $targetResults += $tr
            continue
        }

        $enumerate = ([bool]$target.perNetworkInterface) -or ([bool]$target.perMonitor)
        $ordered = Get-HklmFirstOrder (@($target.paths) | ForEach-Object { [string]$_ })

        $pathResults = @()
        foreach ($p in $ordered) {
            $pathResults += (Read-OnePath -Path $p -ValueName ([string]$target.valueName) `
                -KeyExistenceOnly ([bool]$target.keyExistenceOnly) -EnumerateSubKeys $enumerate)
        }
        $tr.paths = $pathResults

        # Fold to the effective reading the detection engine would see.
        $winner = $null
        foreach ($pr in $pathResults) {
            if ($pr.status -eq 'Present' -or $pr.status -eq 'KeyPresent') { $winner = $pr; break }
        }
        if ($null -ne $winner) {
            $tr.status = $winner.status
            $tr.effectiveValue = $winner.value
            $tr.effectivePath = $winner.path
            $tr.valueKind = $winner.valueKind
        } elseif ($pathResults.Count -eq 0) {
            # A registry target declaring no paths is a catalog defect, not a missing key. Must not
            # fold to KeyMissing, where it would be indistinguishable from a real absent reading.
            $tr.status = 'Error'
            $tr.note = 'Target declares no registry paths.'
        } elseif (@($pathResults | Where-Object { $_.status -eq 'ValueAbsent' }).Count -gt 0) {
            $tr.status = 'ValueAbsent'
        } elseif (@($pathResults | Where-Object { $_.status -eq 'Error' }).Count -eq $pathResults.Count) {
            $tr.status = 'Error'
        } else {
            $tr.status = 'KeyMissing'
        }

        # Targets needing a reduction (REG_BINARY byte/bitmask, packed composite string) are
        # recorded RAW. The reduction is replayed later against Winhance.Core's RegTargetReader
        # rather than re-implemented here, where it could silently diverge.
        if (($null -ne $target.byteIndex) -or ([bool]$target.byteOnly) -or
            ($null -ne $target.bitMask) -or (-not [string]::IsNullOrEmpty([string]$target.compositeStringKey))) {
            $tr.note = 'Raw value recorded; catalog reduction (byte/bitmask/composite) not applied here.'
        }

        if ($counts.Contains($tr.status)) { $counts[$tr.status]++ }
        $targetResults += $tr
    }

    $results += [ordered]@{
        id      = [string]$setting.id
        targets = $targetResults
    }
}
Write-Progress -Activity 'Probing catalog targets' -Completed

# =============================================================================================
# Scheduled tasks -- read-only, best effort. Separated from the registry pass so a failure here
# can never affect the registry results.
# =============================================================================================

$taskResults = @()
foreach ($setting in $settings) {
    foreach ($target in @($setting.targets)) {
        if ($target.kind -ne 'Task') { continue }
        $entry = [ordered]@{
            settingId = [string]$setting.id
            key       = [string]$target.key
            taskPath  = [string]$target.taskPath
            state     = $null
            enabled   = $null
            error     = $null
        }
        try {
            $leaf = Split-Path -Leaf ([string]$target.taskPath)
            $folder = Split-Path -Parent ([string]$target.taskPath)
            if ([string]::IsNullOrEmpty($folder)) { $folder = '\' }
            # Get-ScheduledTask -TaskPath wants a leading AND trailing backslash; a manifest path
            # authored without the leading one would silently match nothing.
            if (-not $folder.StartsWith('\')) { $folder = '\' + $folder }
            if (-not $folder.EndsWith('\')) { $folder = $folder + '\' }
            $task = Get-ScheduledTask -TaskName $leaf -TaskPath $folder -ErrorAction Stop
            $entry.state = [string]$task.State
            $entry.enabled = ($task.State -ne 'Disabled')
        } catch {
            $entry.error = [string]$_.Exception.Message
        }
        $taskResults += $entry
    }
}

# =============================================================================================
# PowerCfg DEFAULTS -- read-only. The DEFAULT AC/DC index for each built-in power setting is static
# data in the SYSTEM hive under
#   HKLM\SYSTEM\CurrentControlSet\Control\Power\PowerSettings\<subgroup>\<setting>\DefaultPowerSchemeValues\<scheme>
# with ACSettingIndex / DCSettingIndex per scheme. This is the true shipped default WITHOUT the write
# that unhiding a hidden setting would need, so v1's powercfg-skip does not apply to reading defaults.
# Control\Power is readable by a standard user, so no elevation.
# =============================================================================================

function Read-PowerCfgDefaults {
    param([string] $Subgroup, [string] $Setting)

    $result = [ordered]@{ status = 'KeyMissing'; schemes = @(); error = $null }
    try {
        $base = Get-BaseKey 'HKEY_LOCAL_MACHINE'
        if ($null -eq $base) { $result.error = 'no HKLM base key'; $result.status = 'Error'; return $result }

        $sub = $Subgroup.Trim('{', '}')
        $set = $Setting.Trim('{', '}')
        $path = "SYSTEM\CurrentControlSet\Control\Power\PowerSettings\$sub\$set\DefaultPowerSchemeValues"
        $key = $base.OpenSubKey($path, $false)
        if ($null -eq $key) { return $result }  # KeyMissing -- setting not present on this machine

        try {
            $schemeEntries = @()
            foreach ($schemeName in @($key.GetSubKeyNames())) {
                $sk = $key.OpenSubKey($schemeName, $false)
                if ($null -eq $sk) { continue }
                try {
                    # $null -eq means absent, not 0. A REG_DWORD arrives as Int32, so [int] never overflows;
                    # the "never" sentinel 0xFFFFFFFF reads as -1 here, which is exactly how Winhance reads it.
                    $ac = $sk.GetValue('ACSettingIndex', $null)
                    $dc = $sk.GetValue('DCSettingIndex', $null)
                    $schemeEntries += [ordered]@{
                        scheme = [string]$schemeName
                        ac     = $(if ($null -eq $ac) { $null } else { [int]$ac })
                        dc     = $(if ($null -eq $dc) { $null } else { [int]$dc })
                    }
                } finally { $sk.Close() }
            }
            $result.schemes = $schemeEntries
            $result.status = if ($schemeEntries.Count -gt 0) { 'Present' } else { 'NoSchemes' }
        } finally { $key.Close() }
    } catch {
        $result.status = 'Error'
        $result.error = [string]$_.Exception.Message
    }
    return $result
}

$powerCfgDefaults = @()
foreach ($setting in $settings) {
    foreach ($target in @($setting.targets)) {
        if ($target.kind -ne 'PowerCfg') { continue }
        $d = Read-PowerCfgDefaults ([string]$target.subgroupGuid) ([string]$target.settingGuid)
        $powerCfgDefaults += [ordered]@{
            settingId    = [string]$setting.id
            key          = [string]$target.key
            subgroupGuid = [string]$target.subgroupGuid
            settingGuid  = [string]$target.settingGuid
            mode         = [string]$target.mode
            units        = [string]$target.units
            status       = [string]$d.status
            schemes      = $d.schemes
            error        = $d.error
        }
    }
}

# =============================================================================================
# Headline finding: which settings' WindowsDefault state reads ABSENT here while that state's
# StateValue does NOT accept absence. Those are the ones whose detection cannot be right on a
# clean install. No value comparison is involved -- this is purely presence -- so it cannot be
# wrong for the subtle reasons a naive re-implementation of the matcher would be.
# =============================================================================================

function Test-BuildInRanges {
    param($Ranges, [int] $Build, [int] $Revision)
    $list = @($Ranges)
    if ($list.Count -eq 0) { return $true }   # unconditional
    foreach ($r in $list) {
        $minB = [int]$r.minBuild; $minR = [int]$r.minRevision
        $maxB = [int]$r.maxBuild; $maxR = [int]$r.maxRevision
        $geMin = ($Build -gt $minB) -or (($Build -eq $minB) -and ($Revision -ge $minR))
        $leMax = ($Build -lt $maxB) -or (($Build -eq $maxB) -and ($Revision -le $maxR))
        if ($geMin -and $leMax) { return $true }
    }
    return $false
}

# Keyed by joinKey, not key: four targets have an empty Key, and an empty-string hashtable/property name is
# not something to rely on round-tripping through ConvertFrom-Json.
$statusBySettingTarget = @{}
foreach ($r in $results) {
    foreach ($t in $r.targets) { $statusBySettingTarget[($r.id + '|' + $t.joinKey)] = $t.status }
}

# Target metadata, needed to keep several classes of false positive OUT OF THE COUNT. Note they are recorded
# and flagged rather than skipped -- a silently dropped suspect is indistinguishable from a clean result.
$targetMetaBySettingTarget = @{}
foreach ($setting in $settings) {
    foreach ($target in @($setting.targets)) {
        $targetMetaBySettingTarget[([string]$setting.id + '|' + [string]$target.joinKey)] = $target
    }
}

$suspects = @()
foreach ($setting in $settings) {
    $hasFallback = $false
    foreach ($st in @($setting.states)) { if ([bool]$st.isFallback) { $hasFallback = $true } }

    foreach ($st in @($setting.states)) {
        # Roles are per power CONTEXT (Always / AC / DC) as well as per build, so collect the contexts
        # in which this state is the Windows default here rather than reducing to one boolean.
        $wdContexts = @()
        foreach ($role in @($st.roles)) {
            if ([string]$role.kind -ne 'WindowsDefault') { continue }
            # A build-SCOPED role (non-empty appliesTo) is the OS-divergent default -- e.g. the This PC
            # folder settings default Enabled on Windows 10 and Disabled on Windows 11. It must be
            # judged against THIS machine's build or the wrong state is treated as the default.
            if (Test-BuildInRanges $role.appliesTo $machine.buildNumber $machine.ubr) {
                $wdContexts += [string]$role.context
            }
        }
        if ($wdContexts.Count -eq 0) { continue }

        foreach ($prop in @($st.set.PSObject.Properties)) {
            $targetKey = [string]$prop.Name
            $sv = $prop.Value
            if ([bool]$sv.acceptsAbsent) { continue }      # already handles absence correctly
            if ([bool]$sv.acceptsAnyPresent) { continue }

            $lookup = [string]$setting.id + '|' + $targetKey
            $meta = $targetMetaBySettingTarget[$lookup]

            if ($null -eq $meta) {
                # A Set entry naming a target the setting does not declare. Recorded rather than
                # skipped -- silently dropping it would quietly shrink the finding.
                $suspects += [ordered]@{
                    id = [string]$setting.id; control = [string]$setting.control
                    stateLabel = [string]$st.label; contexts = $wdContexts
                    targetKey = $targetKey; targetKind = 'Unknown'; status = 'NoSuchTarget'
                    hasFallback = $hasFallback; hasDetector = ($null -ne $setting.detector)
                    applyOnly = $false; targetAppliesHere = $false; settingAppliesHere = $false
                    perSubKeyTarget = $false; countsTowardFinding = $false
                }
                continue
            }

            $status = $statusBySettingTarget[$lookup]
            if ($status -ne 'ValueAbsent' -and $status -ne 'KeyMissing') { continue }

            # Gates that disqualify a reading from being EVIDENCE of a detection bug. Each is recorded
            # rather than used to skip, so the JSON stays complete and only the headline count narrows.
            #   applyOnly    - excluded from the precedence path's deciding-target selection, so an absent
            #                  reading there proves nothing (it can still matter on a whole-pattern setting).
            #   target build - a target scoped to other builds is not live here and reads absent everywhere.
            #   setting build- likewise for the setting's own availability.
            #   perSubKey    - PerNetworkInterface / PerMonitor mean "all subkeys must match", which
            #                  RegTargetReader does not implement; the parent read is not the real answer.
            $targetLive = Test-BuildInRanges $meta.appliesTo $machine.buildNumber $machine.ubr
            $settingLive = Test-BuildInRanges $setting.availability.builds $machine.buildNumber $machine.ubr
            $perSubKey = ([bool]$meta.perNetworkInterface) -or ([bool]$meta.perMonitor)

            $suspects += [ordered]@{
                id             = [string]$setting.id
                control        = [string]$setting.control
                stateLabel     = [string]$st.label
                contexts       = $wdContexts
                targetKey      = $targetKey
                targetKind     = [string]$meta.kind
                status         = [string]$status
                hasFallback    = $hasFallback
                hasDetector    = ($null -ne $setting.detector)
                applyOnly      = [bool]$meta.applyOnly
                targetAppliesHere  = $targetLive
                settingAppliesHere = $settingLive
                perSubKeyTarget    = $perSubKey
                countsTowardFinding = ((-not [bool]$meta.applyOnly) -and $targetLive -and $settingLive -and (-not $perSubKey))
            }
        }
    }
}

# =============================================================================================
# Write the output file
# =============================================================================================

$document = [ordered]@{
    probeSchemaVersion = $ProbeSchemaVersion
    manifestSchema     = $manifest.schemaVersion
    catalogHash        = [string]$manifest.catalogHash   # ties this result to the exact catalog revision it was run against
    machine            = $machine
    counts             = $counts
    settings           = $results
    scheduledTasks     = $taskResults
    powerCfgDefaults   = $powerCfgDefaults
    absentWindowsDefaultSuspects = $suspects
}

$editionTag = [string]$machine.editionId
if ([string]::IsNullOrEmpty($editionTag)) { $editionTag = 'UnknownEdition' }
$fileName = ('winhance-defaults-probe_{0}.{1}_{2}_{3}_{4}.json' -f `
    $machine.buildNumber, $machine.ubr, $editionTag, $machine.computerName,
    (Get-Date).ToString('yyyyMMdd-HHmmss'))

$candidateDirs = @()
if (-not [string]::IsNullOrEmpty($OutputDir)) { $candidateDirs += $OutputDir }
if (-not [string]::IsNullOrEmpty($PSScriptRoot)) { $candidateDirs += $PSScriptRoot }
$candidateDirs += [System.Environment]::GetFolderPath('Desktop')
$candidateDirs += [string]$env:TEMP

$json = ConvertTo-JsonText $document
$utf8NoBom = New-Object System.Text.UTF8Encoding($false)

$outPath = $null
$writeFailures = @()
foreach ($dir in $candidateDirs) {
    if ([string]::IsNullOrEmpty($dir)) { continue }
    try {
        if (-not (Test-Path -LiteralPath $dir)) { continue }
        # Resolve-Path first: Test-Path and Join-Path resolve against PowerShell's location, but
        # [System.IO.File] resolves against the .NET process working directory, and the two routinely
        # differ. A relative -OutputDir would otherwise write the file somewhere other than reported.
        $fullDir = (Resolve-Path -LiteralPath $dir).ProviderPath
        $attempt = [System.IO.Path]::GetFullPath((Join-Path $fullDir $fileName))
        [System.IO.File]::WriteAllText($attempt, $json, $utf8NoBom)
        $outPath = $attempt
        break
    } catch {
        $writeFailures += ('{0}: {1}' -f $dir, $_.Exception.Message)
    }
}

if ($null -eq $outPath) {
    Write-Host ''
    Write-Host '  FAILED to write the output file to any candidate location.' -ForegroundColor Red
    foreach ($f in $writeFailures) { Write-Host ('    {0}' -f $f) -ForegroundColor Red }
    Write-Host ('  Tried: {0}' -f ($candidateDirs -join '; ')) -ForegroundColor Red
    exit 4
}

# =============================================================================================
# Human summary
# =============================================================================================

$absentSuspects = @($suspects | Where-Object { $_.countsTowardFinding })
$manifestDefects = @($suspects | Where-Object { $_.status -eq 'NoSuchTarget' })
$excludedSuspects = @($suspects | Where-Object { -not $_.countsTowardFinding -and $_.status -ne 'NoSuchTarget' })
$suspectSettingIds = @($absentSuspects | ForEach-Object { $_.id } | Sort-Object -Unique)
$suspectFallbackIds = @($absentSuspects | Where-Object { $_.hasFallback } |
    ForEach-Object { $_.id } | Sort-Object -Unique)

Write-Host ''
Write-Host 'Registry targets by state' -ForegroundColor Cyan
Write-Host ('  Present     : {0}   (a value is stored)' -f $counts.Present)
Write-Host ('  KeyPresent  : {0}   (key-existence target, key is there)' -f $counts.KeyPresent)
Write-Host ('  ValueAbsent : {0}   (key exists, value is NOT written)' -f $counts.ValueAbsent)
Write-Host ('  KeyMissing  : {0}   (parent key does not exist)' -f $counts.KeyMissing)
Write-Host ('  Error       : {0}' -f $counts.Error)
Write-Host ('  NotProbed   : {0}   (powercfg / scheduled task registry targets)' -f $counts.NotProbed)
$pcWith = @($powerCfgDefaults | Where-Object { $_.status -eq 'Present' }).Count
Write-Host ('  PowerCfg    : {0} of {1} powercfg settings had readable AC/DC defaults in the SYSTEM hive' -f $pcWith, $powerCfgDefaults.Count)
Write-Host ''
Write-Host 'Headline finding' -ForegroundColor Cyan
Write-Host ('  {0} settings have a WindowsDefault state that does NOT accept absence,' -f $suspectSettingIds.Count)
Write-Host '  yet the value it reads is absent on THIS machine.'
Write-Host ('  {0} of those also have a fallback state, so they will be silently misreported' -f $suspectFallbackIds.Count)
Write-Host '  as the fallback rather than shown as Custom.'
Write-Host ('  ({0} further reading(s) were absent but do not count as evidence -- apply-only,' -f $excludedSuspects.Count)
Write-Host '   scoped to another build, or per-subkey. All are in the JSON with the reason.)'
if ($manifestDefects.Count -gt 0) {
    Write-Host ('  NOTE: {0} state value(s) name a target the setting does not declare.' -f $manifestDefects.Count) -ForegroundColor Yellow
}
if ($suspectSettingIds.Count -gt 0) {
    Write-Host ''
    Write-Host '  First few:'
    foreach ($id in ($suspectSettingIds | Select-Object -First 15)) { Write-Host ('    - {0}' -f $id) }
    if ($suspectSettingIds.Count -gt 15) {
        Write-Host ('    ... and {0} more (all of them are in the JSON).' -f ($suspectSettingIds.Count - 15))
    }
}
Write-Host ''
Write-Host 'Wrote:' -ForegroundColor Green
Write-Host ('  {0}' -f $outPath) -ForegroundColor Green
Write-Host ''
Write-Host 'Send that one .json file back. Nothing was written to the registry.'
Write-Host ''

foreach ($k in $baseKeyCache.Keys) { try { $baseKeyCache[$k].Close() } catch { } }
exit 0
