using System.Xml.Linq;

namespace Winhance.Infrastructure.Features.Autounattend;

internal static class AutounattendDocument
{
    public static readonly XNamespace Unattend = "urn:schemas-microsoft-com:unattend";
    public static readonly XNamespace Wcm = "http://schemas.microsoft.com/WMIConfig/2002/State";
    public static readonly XNamespace WinhanceExtensions = "urn:winhance:unattend";

    public const string PlaceholderArchitecture = "amd64";

    private static readonly string[] Passes =
        ["offlineServicing", "windowsPE", "generalize", "specialize", "auditSystem", "auditUser", "oobeSystem"];

    // Windows SIM writes component children in schema order; writers add them in whatever order they run.
    private static readonly string[] ComponentChildOrder =
    [
        "SetupUILanguage", "InputLocale", "SystemLocale", "UserLocale",
        "UserData", "ImageInstall", "DiskConfiguration", "RunSynchronous", "RunAsynchronous",
        "ComputerName", "TimeZone", "ProductKey", "OOBE", "UserAccounts", "AutoLogon", "FirstLogonCommands",
    ];

    private static readonly string[] OobeChildOrder =
    [
        "HideEULAPage", "HideLocalAccountScreen", "HideOEMRegistrationScreen", "HideOnlineAccountScreens",
        "HideWirelessSetupInOOBE", "NetworkLocation", "ProtectYourPC",
    ];

    public static XDocument NewSkeleton()
    {
        var root = new XElement(Unattend + "unattend",
            new XAttribute(XNamespace.Xmlns + "wcm", Wcm.NamespaceName),
            new XComment(" XML Generated by Winhance https://github.com/memstechtips/Winhance "));
        // Empty-string content keeps an unused pass as <settings></settings> rather than a self-closing element.
        foreach (var pass in Passes)
            root.Add(new XElement(Unattend + "settings", new XAttribute("pass", pass), string.Empty));
        // Save(XmlWriter) ignores this declaration and writes the writer's own.
        return new XDocument(new XDeclaration("1.0", "utf-8", null), root);
    }

    public static XElement Pass(this XDocument doc, string pass) =>
        doc.Root!.Elements(Unattend + "settings").First(s => (string?)s.Attribute("pass") == pass);

    public static XElement Component(this XElement settings, string name)
    {
        var existing = settings.Elements(Unattend + "component").FirstOrDefault(c => (string?)c.Attribute("name") == name);
        if (existing is not null)
            return existing;

        var component = new XElement(Unattend + "component",
            new XAttribute("name", name),
            new XAttribute("processorArchitecture", PlaceholderArchitecture),
            new XAttribute("publicKeyToken", "31bf3856ad364e35"),
            new XAttribute("language", "neutral"),
            new XAttribute("versionScope", "nonSxS"));
        settings.Add(component);
        return component;
    }

    public static XElement Child(this XElement component, string name) =>
        Ordered(component, name, ComponentChildOrder);

    // Not called Element: XElement.Element(XName) is an instance method and would win the overload.
    public static XElement ElementPath(this XElement component, string path)
    {
        var names = path.Split('/');
        var element = component.Child(names[0]);
        foreach (var name in names.Skip(1))
            element = element.Name == Unattend + "OOBE" ? Ordered(element, name, OobeChildOrder) : Append(element, name);
        return element;
    }

    public static void SetSetting(this XElement parent, string name, string value) =>
        Append(parent, name).Value = value;

    public static void SetOobe(this XElement shellSetup, string name, string value) =>
        shellSetup.ElementPath("OOBE/" + name).Value = value;

    public static void AddRunSynchronousCommand(this XElement component, string path, string? description = null)
    {
        var list = component.Child("RunSynchronous");
        var command = new XElement(Unattend + "RunSynchronousCommand",
            new XAttribute(Wcm + "action", "add"),
            new XElement(Unattend + "Order", list.Elements(Unattend + "RunSynchronousCommand").Count() + 1));
        if (description is not null)
            command.Add(new XElement(Unattend + "Description", description));
        command.Add(new XElement(Unattend + "Path", path));
        list.Add(command);
    }

    public static void AddFirstLogonCommand(this XElement shellSetup, string commandLine, string? description = null)
    {
        var list = shellSetup.Child("FirstLogonCommands");
        var command = new XElement(Unattend + "SynchronousCommand",
            new XElement(Unattend + "Order", list.Elements(Unattend + "SynchronousCommand").Count() + 1));
        if (description is not null)
            command.Add(new XElement(Unattend + "Description", description));
        command.Add(new XElement(Unattend + "CommandLine", commandLine));
        list.Add(command);
    }

    public static XElement Extensions(this XDocument doc)
    {
        var extensions = doc.Root!.Element(WinhanceExtensions + "Extensions");
        if (extensions is null)
        {
            extensions = new XElement(WinhanceExtensions + "Extensions");
            doc.Root.Add(extensions);
        }
        return extensions;
    }

    private static XElement Append(XElement parent, string name)
    {
        var existing = parent.Element(Unattend + name);
        if (existing is not null)
            return existing;

        var element = new XElement(Unattend + name);
        parent.Add(element);
        return element;
    }

    private static XElement Ordered(XElement parent, string name, string[] order)
    {
        var existing = parent.Element(Unattend + name);
        if (existing is not null)
            return existing;

        var element = new XElement(Unattend + name);
        var rank = Array.IndexOf(order, name);
        if (rank < 0)
        {
            parent.Add(element);
            return element;
        }

        var later = parent.Elements().FirstOrDefault(e => Array.IndexOf(order, e.Name.LocalName) > rank);
        if (later is null)
            parent.Add(element);
        else
            later.AddBeforeSelf(element);
        return element;
    }
}
