using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Winhance.Localization.Generator;

// The members go inside LocKey: a nested type reaches its containing type's private constructor, which is what
// stops the rest of the assembly forging a key.
[Generator]
public sealed class LocalizationKeyGenerator : IIncrementalGenerator
{
    private const string Namespace = "Winhance.Core.Features.Common.Localization";
    private static readonly char[] Underscore = { '_' };
    private const string FileName = "en.json";

    // A warning, not an error: two spellings of one key is a data smell in en.json, not a reason to stop the build.
    private static readonly DiagnosticDescriptor DuplicateIdentifier = new(
        id: "WINLOC001",
        title: "Two localization keys map to one identifier",
        messageFormat: "Keys '{0}' and '{1}' both map to LocKey.{2}; using '{0}'. Remove the other from all 29 files.",
        category: "Localization",
        defaultSeverity: DiagnosticSeverity.Warning,
        isEnabledByDefault: true);

    private static readonly DiagnosticDescriptor MissingFile = new(
        id: "WINLOC002",
        title: "en.json was not supplied to the generator",
        messageFormat: "No AdditionalFiles entry named en.json. Add it to the project that consumes LocKey.",
        category: "Localization",
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    private static readonly DiagnosticDescriptor Unparsable = new(
        id: "WINLOC003",
        title: "en.json could not be parsed",
        messageFormat: "en.json is not a flat JSON object of string values: {0}",
        category: "Localization",
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var enJson = context.AdditionalTextsProvider
            .Where(static f => string.Equals(
                System.IO.Path.GetFileName(f.Path), FileName, StringComparison.OrdinalIgnoreCase))
            .Select(static (f, ct) => f.GetText(ct)?.ToString())
            .Collect();

        context.RegisterSourceOutput(enJson, Emit);
    }

    private static void Emit(SourceProductionContext context, ImmutableArray<string?> files)
    {
        var json = files.FirstOrDefault(t => !string.IsNullOrEmpty(t));
        if (json is null)
        {
            context.ReportDiagnostic(Diagnostic.Create(MissingFile, Location.None));
            return;
        }

        IReadOnlyDictionary<string, string> entries;
        try
        {
            entries = FlatJson.Parse(json);
        }
        catch (Exception ex)
        {
            context.ReportDiagnostic(Diagnostic.Create(Unparsable, Location.None, ex.Message));
            return;
        }

        var root = new Node();
        var claimed = new Dictionary<string, string>(StringComparer.Ordinal);

        foreach (var pair in entries.OrderBy(e => e.Key, StringComparer.Ordinal))
        {
            // _Meta_* keys are read straight off the dictionary by LocalizationService, so they get no member.
            if (pair.Key.Length == 0 || pair.Key[0] == '_') continue;

            var path = IdentifierPath(pair.Key);
            if (path.Count == 0) continue;

            var dotted = string.Join(".", path);
            if (claimed.TryGetValue(dotted, out var already))
            {
                var keep = already.Length <= pair.Key.Length ? already : pair.Key;
                var drop = keep == already ? pair.Key : already;
                context.ReportDiagnostic(Diagnostic.Create(
                    DuplicateIdentifier, Location.None, keep, drop, dotted));
                if (keep == already) continue;
            }
            claimed[dotted] = pair.Key;

            var node = root;
            for (int i = 0; i < path.Count - 1; i++) node = node.Child(path[i]);
            node.Leaves[path[path.Count - 1]] = (pair.Key, pair.Value);
        }

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace " + Namespace + ";");
        sb.AppendLine();
        sb.AppendLine("public readonly partial record struct LocKey");
        sb.AppendLine("{");
        foreach (var child in root.Children.OrderBy(c => c.Key, StringComparer.Ordinal))
            WriteClass(sb, child.Key, child.Value, 1);
        sb.AppendLine("}");

        context.AddSource("LocKey.Generated.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static void WriteClass(StringBuilder sb, string name, Node node, int depth)
    {
        var pad = new string(' ', depth * 4);
        sb.AppendLine(pad + "public static class " + name);
        sb.AppendLine(pad + "{");

        foreach (var leaf in node.Leaves.OrderBy(l => l.Key, StringComparer.Ordinal))
        {
            sb.AppendLine(pad + "    /// <summary>" + XmlEscape(leaf.Value.English) + "</summary>");
            sb.AppendLine(pad + "    public static LocKey " + leaf.Key
                              + " => new(\"" + leaf.Value.Key.Replace("\\", "\\\\").Replace("\"", "\\\"") + "\");");
        }

        foreach (var child in node.Children.OrderBy(c => c.Key, StringComparer.Ordinal))
            WriteClass(sb, child.Key, child.Value, depth + 1);

        sb.AppendLine(pad + "}");
    }

    // Setting_theme-wallpaper_Name          -> [Setting, ThemeWallpaper, Name]
    // Setting_autounattend-edition_Option_0 -> [Setting, AutounattendEdition, Option0]
    // AutounattendAccounts_Group            -> [AutounattendAccounts, Group]
    //
    // Depth is fixed. Nesting every segment does not compile: 59 keys are a prefix of another (Common_CustomState
    // beside Common_CustomState_ShortLabel), and a name cannot be a nested class and a property at once.
    internal static List<string> IdentifierPath(string key)
    {
        var segments = key.Split(Underscore, StringSplitOptions.RemoveEmptyEntries);
        if (segments.Length < 2) return new List<string>();

        var top = Pascal(segments[0]);
        if (top.Length == 0) return new List<string>();

        if (top == "Setting" && segments.Length >= 3)
        {
            var id = Pascal(segments[1]);
            var member = Join(segments, 2);
            return id.Length == 0 || member.Length == 0
                ? new List<string>()
                : new List<string> { top, id, member };
        }

        var flat = Join(segments, 1);
        return flat.Length == 0 ? new List<string>() : new List<string> { top, flat };
    }

    private static string Join(string[] segments, int from)
    {
        var sb = new StringBuilder();
        for (var i = from; i < segments.Length; i++) sb.Append(Pascal(segments[i]));
        return sb.ToString();
    }

    // Catalog ids are [a-z0-9-] only, so for Setting_* keys dropping non-identifier characters is lossless.
    private static string Pascal(string segment)
    {
        var sb = new StringBuilder(segment.Length);
        var upperNext = true;
        foreach (var c in segment)
        {
            if (c == '-' || c == ' ') { upperNext = true; continue; }
            if (!char.IsLetterOrDigit(c)) continue;
            sb.Append(upperNext ? char.ToUpperInvariant(c) : c);
            upperNext = false;
        }
        return sb.ToString();
    }

    private static string XmlEscape(string value)
    {
        var oneLine = value.Replace("\r", " ").Replace("\n", " ");
        while (oneLine.Contains("  ")) oneLine = oneLine.Replace("  ", " ");
        return oneLine.Trim()
            .Replace("&", "&amp;")
            .Replace("<", "&lt;")
            .Replace(">", "&gt;");
    }

    private sealed class Node
    {
        public Dictionary<string, Node> Children { get; } = new(StringComparer.Ordinal);
        public Dictionary<string, (string Key, string English)> Leaves { get; } = new(StringComparer.Ordinal);

        public Node Child(string name)
        {
            if (!Children.TryGetValue(name, out var child)) Children[name] = child = new Node();
            return child;
        }
    }
}
