namespace Winhance.Core.Features.SoftwareApps.Models;

public static class EdgeRemovalScript
{
    public static string GetScript()
    {
        return @"
# EdgeRemoval.ps1
# Standalone script to remove Microsoft Edge
# Source: Winhance (https://github.com/memstechtips/Winhance)
# Portions of this script are derived from:
# FR33THY: https://github.com/FR33THYFR33THY/Ultimate-Windows-Optimization-Guide/blob/main/6%20Windows/14%20Edge.ps1
# ishad0w: https://gist.github.com/ishad0w/d25ca52eb04dbefba8087a344a69c79c

# Generated by Winhance on "
            + DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss")
            + @"

# Check if script is running as Administrator
If (!([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]""Administrator"")) {
    Try {
        Start-Process PowerShell.exe -ArgumentList (""-NoProfile -ExecutionPolicy Bypass -File `""{0}`"""" -f $PSCommandPath) -Verb RunAs
        Exit
    }
    Catch {
        Write-Host ""Failed to run as Administrator. Please rerun with elevated privileges.""
        Exit
    }
}

# Setup logging
$logFolder = ""C:\ProgramData\Winhance\Logs""
$logFile = ""$logFolder\EdgeRemovalLog.txt""

# Create log directory if it doesn't exist
if (!(Test-Path $logFolder)) {
    New-Item -ItemType Directory -Path $logFolder -Force | Out-Null
}

# Function to write to log file
function Write-Log {
    param (
        [string]$Message
    )

    # Check if log file exists and is over 500KB (512000 bytes)
    if ((Test-Path $logFile) -and (Get-Item $logFile).Length -gt 512000) {
        Remove-Item $logFile -Force -ErrorAction SilentlyContinue
        $timestamp = Get-Date -Format ""yyyy-MM-dd HH:mm:ss""
        ""$timestamp - Log rotated - previous log exceeded 500KB"" | Out-File -FilePath $logFile
    }

    $timestamp = Get-Date -Format ""yyyy-MM-dd HH:mm:ss""
    ""$timestamp - $Message"" | Out-File -FilePath $logFile -Append
}

# Helper function to get Legacy Edge packages
function Get-LegacyEdgePackages {
    $legacyRegPath = ""HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Component Based Servicing\Packages""
    return Get-ChildItem -Path $legacyRegPath -Name -ErrorAction SilentlyContinue | Where-Object { $_ -match ""Microsoft-Windows-Internet-Browser-Package"" -and $_ -match ""~~"" }
}

# Function to test if Legacy Edge is installed
function Test-LegacyEdgeInstalled {
    $packages = Get-LegacyEdgePackages

    if ($packages) {
        foreach ($package in $packages) {
            $packageInfo = & dism /online /Get-PackageInfo /PackageName:$package 2>$null
            if ($packageInfo -match ""State.*Installed"") {
                return $true
            }
        }
    }
    return $false
}

# Function to test if Chromium Edge is installed
function Test-ChromiumEdgeInstalled {
    # Check folders first (fastest)
    $edgeFolders = @(""Edge"", ""EdgeCore"", ""EdgeUpdate"")
    $programFiles = @($env:ProgramFiles, ${env:ProgramFiles(x86)})

    foreach ($pf in $programFiles) {
        foreach ($folder in $edgeFolders) {
            if (Test-Path ""$pf\Microsoft\$folder"") {
                return $true
            }
        }
    }

    # Fallback: Check installed programs
    try {
        $edgeApp = Get-WmiObject -Class Win32_InstalledStoreProgram -Filter ""Name like '%Microsoft.MicrosoftEdge.Stable%'"" -ErrorAction SilentlyContinue
        return $edgeApp -ne $null
    } catch {
        return $false
    }
}

# Function to stop Edge-related processes
function Stop-EdgeProcesses {
    Write-Log ""Stopping Edge-related processes and services""
    $stop = ""MicrosoftEdgeUpdate"", ""OneDrive"", ""WidgetService"", ""Widgets"", ""msedge"", ""Resume"", ""CrossDeviceResume"", ""msedgewebview2""
    $stop | ForEach-Object {
        $processCount = (Get-Process -Name $_ -ErrorAction SilentlyContinue).Count
        if ($processCount -gt 0) {
            Stop-Process -Name $_ -Force -ErrorAction SilentlyContinue
            Write-Log ""Stopped $processCount instance(s) of $_""
        }
    }
}

# Function to remove Legacy Edge
function Remove-LegacyEdge {
    Write-Log ""Starting Legacy Edge/UWP Edge removal process""
    # Query registry for Edge Legacy package
    $packages = Get-LegacyEdgePackages
    $edgeLegacyPackageVersion = $packages | Select-Object -First 1
    $packagePath = ""HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Component Based Servicing\Packages\$edgeLegacyPackageVersion""
    # Set registry visibility
    Set-ItemProperty -Path $packagePath -Name ""Visibility"" -Value 1 -Type DWord -Force -ErrorAction SilentlyContinue
    # Remove owners registry entries
    $ownersPath = ""$packagePath\Owners""
    if (Test-Path $ownersPath) { Remove-Item -Path $ownersPath -Recurse -Force -ErrorAction SilentlyContinue }
    Write-Log ""Removing Legacy Edge package via DISM""
    & dism /online /Remove-Package /PackageName:$edgeLegacyPackageVersion >$null 2>&1
    # Remove Legacy UWP Edge package
    Write-Log ""Removing Legacy UWP Edge package""
    Get-AppxPackage Microsoft.MicrosoftEdge | Remove-AppxPackage -ErrorAction SilentlyContinue | Out-Null
    Write-Log ""Legacy Edge/UWP Edge removal process completed""
}

# Function to remove Chromium Edge and EdgeUpdate
function Remove-ChromiumEdge {
    # Remove Chromium Edge
    Write-Log ""Starting Edge Chromium uninstallation process""
    # Folder and file to allow uninstall of Edge Chromium Browser
    Write-Log ""Creating temporary directory for Edge uninstallation""
    $edgePath = ""$env:SystemRoot\SystemApps\Microsoft.MicrosoftEdge_8wekyb3d8bbwe""
    New-Item -Path $edgePath -ItemType Directory -ErrorAction SilentlyContinue | Out-Null
    New-Item -Path $edgePath -ItemType File -Name ""MicrosoftEdge.exe"" -ErrorAction SilentlyContinue | Out-Null
    # Get Edge Uninstall Strings for Enterprise MSI version or normal version (they require different handling)
    Write-Log ""Searching for Edge uninstall strings in registry""
    $uninstallKeys = Get-ChildItem ""HKLM:\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall""
    $edgeUninstallCount = 0
    foreach ($key in $uninstallKeys) {
        $displayName = (Get-ItemProperty $key.PSPath -ErrorAction SilentlyContinue).DisplayName
        if ($displayName -like ""*Microsoft Edge*"") {
            $uninstallString = (Get-ItemProperty $key.PSPath).UninstallString
            if ($uninstallString) {
                $edgeUninstallCount++
                if ($uninstallString -like ""*msiexec*"") {
                    # Uninstalls Enterprise MSI version
                    Write-Log ""Executing MSI uninstaller for Edge""
                    Start-Process cmd.exe ""/c $uninstallString /quiet"" -WindowStyle Hidden -Wait | Out-Null
                } else {
                    # Uninstalls normal version
                    Write-Log ""Executing standard uninstaller for Edge""
                    Start-Process cmd.exe ""/c $uninstallString --force-uninstall --silent"" -WindowStyle Hidden -Wait | Out-Null
                }
            }
        }
    }
    if ($edgeUninstallCount -eq 0) {
        Write-Log ""No Edge uninstall entries found in registry""
    } else {
        Write-Log ""Executed $edgeUninstallCount Edge uninstaller(s)""
    }
    # Remove UWP Edge Chromium package
    Write-Log ""Removing UWP Edge Chromium package""
    Get-AppxPackage *Microsoft.MicrosoftEdge.Stable* | Remove-AppxPackage -ErrorAction SilentlyContinue | Out-Null
    # Cleanup: Remove folder and file we created earlier
    Write-Log ""Cleaning up temporary Edge directory""
    Remove-Item -Recurse -Force $edgePath -ErrorAction SilentlyContinue | Out-Null
    Write-Log ""Edge Chromium uninstallation process completed""

    # Remove EdgeUpdate
    Write-Log ""Starting EdgeUpdate removal process""
    # Find EdgeUpdate executables
    Write-Log ""Searching for EdgeUpdate executables""
    $edgeupdate = @()
    $searchPaths = @(""LocalApplicationData"", ""ProgramFilesX86"", ""ProgramFiles"")
    foreach ($pathType in $searchPaths) {
        $folder = [Environment]::GetFolderPath($pathType)
        $searchPattern = ""$folder\Microsoft\EdgeUpdate\*.*.*.*\MicrosoftEdgeUpdate.exe""
        $foundFiles = Get-ChildItem $searchPattern -Recurse -ErrorAction SilentlyContinue
        if ($foundFiles) {
            $edgeupdate += $foundFiles.FullName
        }
    }
    if ($edgeupdate.Count -gt 0) {
        Write-Log ""Found $($edgeupdate.Count) EdgeUpdate executable(s)""
    } else {
        Write-Log ""No EdgeUpdate executables found""
    }
    # Backup ClientState registry if it exists (important, or else webview won't work)
    $backupRegFile = ""$env:TEMP\EdgeUpdate_ClientState_Backup_$(Get-Date -Format 'yyyyMMdd_HHmmss').reg""
    $clientStatePath = ""HKLM:\SOFTWARE\WOW6432Node\Microsoft\EdgeUpdate\ClientState""
    if (Test-Path $clientStatePath) {
        Write-Log ""Backing up EdgeUpdate ClientState registry""
        cmd /c ""reg export `""HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\EdgeUpdate\ClientState`"" `""$backupRegFile`"" /y"" 2>$null
        if (Test-Path $backupRegFile) {
            Write-Log ""Successfully created registry backup at $backupRegFile""
        } else {
            Write-Log ""Warning: Failed to create registry backup""
        }
    } else {
        Write-Log ""No EdgeUpdate ClientState registry found to backup""
    }
    # Clean registry entries
    Write-Log ""Removing EdgeUpdate registry entries""
    $registryPaths = @(
        ""HKLM:\SOFTWARE"", ""HKLM:\SOFTWARE\Policies"", ""HKLM:\SOFTWARE\WOW6432Node"", ""HKLM:\SOFTWARE\WOW6432Node\Policies""
    )
    $removedRegCount = 0
    foreach ($location in $registryPaths) {
        $regPath = ""$location\Microsoft\EdgeUpdate""
        if (Test-Path $regPath) {
            Remove-Item $regPath -Recurse -Force -ErrorAction SilentlyContinue
            $removedRegCount++
        }
    }
    Write-Log ""Removed EdgeUpdate registry entries from $removedRegCount location(s)""
    # Uninstall EdgeUpdate executables
    Write-Log ""Processing EdgeUpdate uninstallation""
    foreach ($path in $edgeupdate) {
        if (Test-Path $path) {
            # Unregister service
            Write-Log ""Unregistering EdgeUpdate service from $path""
            Start-Process -FilePath $path -ArgumentList ""/unregsvc"" -Wait -WindowStyle Hidden -ErrorAction SilentlyContinue
            # Wait for processes to finish
            $waitCount = 0
            do {
                Start-Sleep 3
                $runningProcesses = Get-Process -Name ""setup"", ""MicrosoftEdge*"" -ErrorAction SilentlyContinue | Where-Object { $_.Path -like ""*\Microsoft\Edge*"" }
            } while ($runningProcesses -and $waitCount++ -lt 20)
            # Run uninstall if file still exists
            if (Test-Path $path) {
                Write-Log ""Running EdgeUpdate uninstaller from $path""
                Start-Process -FilePath $path -ArgumentList ""/uninstall"" -Wait -WindowStyle Hidden -ErrorAction SilentlyContinue
            }
        }
    }
    # Restore ClientState backup
    if ((Test-Path $backupRegFile)) {
        Write-Log ""Restoring EdgeUpdate ClientState registry from backup""
        cmd /c ""reg import `""$backupRegFile`"""" 2>$null
        Remove-Item $backupRegFile -ErrorAction SilentlyContinue
        Write-Log ""Registry restore completed and backup file cleaned up""
    } else {
        Write-Log ""No registry backup file found to restore""
    }
    Write-Log ""EdgeUpdate removal process completed""
}

Write-Host ""Starting Edge removal process. See $logFile for details.""

# Check for Edge installations first
Write-Log ""Checking for Edge installations...""

$legacyInstalled = Test-LegacyEdgeInstalled
$chromiumInstalled = Test-ChromiumEdgeInstalled

if (-not $legacyInstalled -and -not $chromiumInstalled) {
    Write-Log ""No Edge installations detected. Exiting.""
    Write-Host ""No Edge installations found. Script exiting.""
    exit 0
}

$removedSomething = $false

if ($legacyInstalled) {
    Write-Log ""Legacy Edge detected. Proceeding with removal.""
    Stop-EdgeProcesses
    Remove-LegacyEdge
    $removedSomething = $true
}

if ($chromiumInstalled) {
    Write-Log ""Chromium Edge detected. Proceeding with removal.""
    Stop-EdgeProcesses
    Remove-ChromiumEdge
    $removedSomething = $true
}

# Only do cleanup if we removed something
if ($removedSomething) {
    # Cleanup: Remove folders containing Edge (Edge, EdgeCore, EdgeUpdate) or Temp but exclude EdgeWebView
    Write-Log ""Starting cleanup of Microsoft Edge folders""
    $edgeFolders = Get-ChildItem -Path ""$env:SystemDrive\Program Files (x86)\Microsoft"" -Directory -ErrorAction SilentlyContinue |
    Where-Object { ($_.Name -like ""*Edge*"" -or $_.Name -like ""*Temp*"") -and $_.Name -notlike ""*EdgeWebView*"" }
    if ($edgeFolders) {
        Write-Log ""Found $($edgeFolders.Count) Edge-related folder(s) to remove""
        $edgeFolders | Remove-Item -Recurse -Force -ErrorAction SilentlyContinue
        Write-Log ""Cleanup of Microsoft Edge folders completed""
    } else {
        Write-Log ""No Edge-related folders found to clean up""
    }
}

Write-Log ""Done.""
Write-Host ""Done. See $logFile for details.""

";
    }
}
